--ISSUES :
--
--TRANSACTION AND PROCEDURE DIFFERENCE?

--FIGURE OUT DEALING WITH NEW DRUG

CREATE OR REPLACE TRANSACTION TEST_UPDATE
AS
BEGIN
	
	CREATE TABLE DESPENCES LIKE DRUG_PER_LOC;
	CREATE TABLE PURCHASES LIKE DRUG_PER_LOC;
	CREATE TABLE DISCARDS LIKE DRUG_PER_LOC;
	CREATE TABLE TRANSFERS LIKE DRUG_PER_LOC;
	
	BULK
	INSERT DESPENCES
	FROM "C:\file_location"
	WITH
		(
		FIELDDELIMITER = ",",
		ROWTERMINATOR = "\N"
		)
	GO
	
	BULK
	INSERT PURCHASES
	FROM "C:\file_location"
	WITH
		(
		FIELDDELIMITER = ",",
		ROWTERMINATOR = "\N"
		)
	GO
	
	BULK
	INSERT DISCARDS
	FROM "C:\file_location"
	WITH
		(
		FIELDDELIMITER = ",",
		ROWTERMINATOR = "\N"
		)
	GO

	BULK
	INSERT TRANSFERS
	FROM "C:\file_location"
	WITH
		(
		FIELDDELIMITER = ",",
		ROWTERMINATOR = "\N"
		)
	GO

	--RENAME DRUG_PER_LOC TO OLD_DRUG_PER_LOC;
	CREATE TABLE NEW_DRUG_PER_LOC LIKE DRUG_PER_LOC;
	INSERT INTO NEW_DRUG_PER_LOC
		SELECT O.Ctr_loc, O.Dname, O.Par_lvl, O.Flag, (O.Count + U.Count) AS Count
		FROM DRUG_PER_LOC AS O, 
			(	SELECT	T.Dname, SUM(T.Count, P.Count, DE.Count, DI.Count)
				FROM	DISCARDS AS DI, PURCHASES AS P, TRANSFERS AS T, DESPENCES AS DE
				WHERE	DI.Dname=DE.Dname AND DI.Dname=P.Dname AND DI.Dname=T.Dname;) AS U
		WHERE O.Dname=U.Dname;
	RENAME DRUG_PER_LOC TO OLD_DRUG_PER_LOC;
	RENAME NEW_DRUG_PER_LOC TO DRUG_PER_LOC;
END
 

