source 'https://rubygems.org'
gem 'sinatra'
gem 'sinatra-contrib'
gem 'sinatra-flash'
gem 'activerecord'
gem 'sqlite3'
gem 'rack-ssl'
gem 'chartkick'
gem 'thin'
gem 'rubyXL'
gem 'spreadsheet'
gem 'warden'
gem 'data_mapper'
gem 'dm-sqlite-adapter'
gem 'bcrypt'
gem 'whenever', :require => false
